const serviceData = [
    {
        id: 1,
        title: "Haircut Services",
        service: "Growming Haircut",
        kethar: "",
        price: "75K",
        description: "Edukasi, Haircut, Styling with Product, Foto Studio",
    },
    {
        id: 2,
        title: "Haircut Services",
        service: "Growming Special",
        kethar: "",
        price: "100K",
        description: "Edukasi, Haircut, Black mask, Hairwash, Hot towel, Facial face, Styling with Product, Foto Studio",
    },
    {
        id: 3,
        title: "Haircolor Services",
        service: "Black Haircolor",
        kethar: "",
        price: "100K",
        description: "",
    },
    {
        id: 4,
        title: "Haircolor Services",
        service: "Basic Haircolor",
        kethar: "",
        price: "200K",
        description: "",
    },
    {
        id: 5,
        title: "Haircolor Services",
        service: "Fashion Haircolor",
        kethar: "Start From",
        price: "200K",
        description: "",
    },
    {
        id: 6,
        title: "Shaving & Grooming",
        service: "Shaving",
        kethar: "",
        price: "45K",
        description: "",
    },
    {
        id: 7,
        title: "Shaving & Grooming",
        service: "Hair Tattoo",
        kethar: "",
        price: "35K",
        description: "",
    },
    {
        id: 8,
        title: "Shaving & Grooming",
        service: "Beard Trimming",
        kethar: "",
        price: "35K",
        description: "",
    },
    {
        id: 9,
        title: "Hair Treatment",
        service: "Cream Bath",
        kethar: "",
        price: "100K",
        description: "",
    },
    {
        id: 10,
        title: "Hair Treatment",
        service: "Hair Perming",
        kethar: "Start From",
        price: "350K",
        description: "",
    },
    {
        id: 11,
        title: "Hair Treatment",
        service: "Down Perming",
        kethar: "Start From",
        price: "350K",
        description: "",
    },
    {
        id: 12,
        title: "Hair Treatment",
        service: "Smoothing",
        kethar: "Start From",
        price: "350K",
        description: "",
    },
    {
        id: 13,
        title: "Hair Treatment",
        service: "Conrow",
        kethar: "Start From",
        price: "350K",
        description: "",
    },
];

export default serviceData;
